swagger: '2.0'
info:
  version: 1.0.0
  title: mathei-api
  description: mathei server
basePath: /api/v1
definitions:
  TodoItem:
    type: object
    required:
      - description
    properties:
      description:
        type: string
      completed:
        type: boolean
  Foo:
    type: object
    required: null
    properties:
      someInt:
        type: number
      someString:
        type: string
paths:
  /todoitems:
    get:
      tags:
        - TodoItem
      summary: Retrieves all todoitems.
      responses:
        '200':
          description: Success
        '400':
          description: Bad Request
        '404':
          description: Notfound
        '500':
          description: Internal Server Error
    post:
      tags:
        - TodoItem
      summary: Creates a new todoitem.
      consumes:
        - application/json
      parameters:
        - in: body
          name: todoitem
          description: The todoitem to create.
          schema:
            $ref: '#/definitions/TodoItem'
      responses:
        '200':
          description: OK
        '201':
          description: CREATED
        '500':
          description: Internal Server Error
  '/todoitems/{id}':
    get:
      tags:
        - TodoItem
      summary: Retrieves a single todoitem by id.
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the TodoItem to retrieve.
          type: string
      responses:
        '200':
          description: Return the todoitem with the specified id
        '404':
          description: TodoItem not found
        '500':
          description: Internal Server Error
    put:
      tags:
        - TodoItem
      summary: Updates todoitem.
      consumes:
        - application/json
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the TodoItem to update.
          type: string
        - in: body
          name: todoitem
          description: The todoitem to update.
          schema:
            $ref: '#/definitions/TodoItem'
      responses:
        '200':
          description: OK
        '500':
          description: Internal Server Error
    delete:
      tags:
        - TodoItem
      summary: Deletes a single todoitem by id.
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the TodoItem to delete.
          type: string
      responses:
        '204':
          description: No Content
        '404':
          description: TodoItem not found
        '500':
          description: Internal Server Error
  /foos:
    get:
      tags:
        - Foo
      summary: Retrieves all foos.
      responses:
        '200':
          description: Success
        '400':
          description: Bad Request
        '404':
          description: Notfound
        '500':
          description: Internal Server Error
    post:
      tags:
        - Foo
      summary: Creates a new foo.
      consumes:
        - application/json
      parameters:
        - in: body
          name: foo
          description: The foo to create.
          schema:
            $ref: '#/definitions/Foo'
      responses:
        '200':
          description: OK
        '201':
          description: CREATED
        '500':
          description: Internal Server Error
  '/foos/{id}':
    get:
      tags:
        - Foo
      summary: Retrieves a single foo by id.
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the Foo to retrieve.
          type: string
      responses:
        '200':
          description: Return the foo with the specified id
        '404':
          description: Foo not found
        '500':
          description: Internal Server Error
    put:
      tags:
        - Foo
      summary: Updates foo.
      consumes:
        - application/json
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the Foo to update.
          type: string
        - in: body
          name: foo
          description: The foo to update.
          schema:
            $ref: '#/definitions/Foo'
      responses:
        '200':
          description: OK
        '500':
          description: Internal Server Error
    delete:
      tags:
        - Foo
      summary: Deletes a single foo by id.
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the Foo to delete.
          type: string
      responses:
        '204':
          description: No Content
        '404':
          description: Foo not found
        '500':
          description: Internal Server Error
